ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from . import views

app_name = 'ecommerce'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', auth_views.LoginView.as_view(
        template_name='ecommerce/registration/login.html'), name='login'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(
        next_page=settings.DEFAULT_REDIRECT_URL), name='logout'),
    url(r'^category/(?P<category_id>\w+)/$', views.category,  name='category'),
    url(r'^orders/$', views.orders_view, name='orders'),
    url(r'^order/(?P<order_id>[0-9]+)/$', views.order_detail,
        name='order'),
    url(r'^order/confirm/(?P<order_id>[0-9]+)/$', views.order_detail,
        name='close_order'),
    url(r'^order/cancel/(?P<order_id>[0-9]+)/$', views.cancel_order,
        name='cancel_order'),
    url(r'^add_to_cart/(?P<product_id>[0-9]+)/$', views.add_product_to_cart_request,
        name='add_to_cart'),
    url(r'^product/(?P<product_id>[0-9]+)/$', views.product_view,
        name='product'),
    url(r'^product/edit/(?P<product_id>[0-9]+)/$', views.edit_product_view,
        name='edit_product'),
    url(r'^supplier/(?P<username>\w+)/$', views.supplier_overview,
        name='supplier_overview'),
    url(r'^product/(?P<product_id>[0-9]+)/review/$', views.submit_review, name='submit_review'),
    url(r'^search/$', views.search_view, name='search_view'),
    url(r'^profile/$', views.profile_view, name='profile')
]

linguaggi_dinamici/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ecommerce/', include('ecommerce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/forms.py
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth.models import User, Group
from django import forms
from django.db.models import Avg
from . import models
from .choices import GROUP_CHOICES, DEFAULT_CURRENCY


class MyUserCreationForm(UserCreationForm):
    group = forms.ChoiceField(choices=GROUP_CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = User
        fields = ("username", "email",)
        field_classes = {'username': UsernameField,
                         "email": forms.EmailField}

    def save(self, commit=True):
        user = super(MyUserCreationForm, self).save(commit=False)

        if commit:
            user.save()

            selected_group_name = self.cleaned_data.get('group')
            selected_group = Group.objects.get(pk=selected_group_name)

            selected_group.user_set.add()

            user.save()
            user.groups.add(selected_group)
            user.save()


class ReviewForm(forms.Form):
    review_image = forms.ImageField(required=False)
    supplier = forms.HiddenInput()
    author = forms.HiddenInput()
    text = forms.CharField(widget=forms.Textarea)
    score = forms.IntegerField(min_value=1, max_value=5, required=True)

    def save(self, commit=True):
        if commit:
            review = models.Review()
            product = self.cleaned_data['product']

            product_model = models.Product.objects.get(pk=product)
            review.product = product_model

            supplier = self.cleaned_data['supplier']
            supplier_model = User.objects.get(username=supplier)
            review.supplier = supplier_model

            author = self.cleaned_data['author']
            author_model = User.objects.get(username=author)
            review.author = author_model

            text_field = self.cleaned_data['text']
            review.text = text_field

            score = self.cleaned_data['score']
            review.score = score

            review.save()

            gallery = models.Gallery()
            gallery.image = self.cleaned_data['review_image']
            if gallery.image:
                gallery.save()
                review.gallery.add(gallery)
                review.save()

            product_model.score = product_model.reviews.aggregate(Avg('score'))['score__avg']
            product_model.save()


class EditProductForm(forms.Form):
    price = forms.CharField(required=True)
    description = forms.CharField(required=True)


class ProductForm(forms.Form):
    name = forms.CharField(required=True)
    manufacturer = forms.CharField(required=True)
    model = forms.CharField(required=True)
    category = forms.CharField(required=True)
    price = forms.CharField(required=True)
    description = forms.CharField(required=True)
    supplier = forms.HiddenInput()
    cover = forms.ImageField(required=True)

    def save(self, commit=True):
        if commit:
            product = models.Product()

            product.name = self.cleaned_data['name']
            product.supplier = User.objects.get(username=self.cleaned_data['supplier'])
            product.manufacturer = models.Manufacturer.objects.get(name=self.cleaned_data['manufacturer'])
            product.model = models.Model.objects.get(name=self.cleaned_data['model'])
            product.price = self.cleaned_data['price']
            product.cover = self.cleaned_data['cover']
            product.currency = DEFAULT_CURRENCY
            product.score = 0;

            product.save()
            product.category.add(models.Category.objects.get(name=self.cleaned_data['category']))
            product.save()

ecommerce/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404
from django.db import transaction
from django.db.utils import IntegrityError
from django.db.models import Q
from django.views import generic
from django.contrib.auth import login, authenticate
from ecommerce.forms import MyUserCreationForm, ReviewForm, ProductForm

from ecommerce.choices import CURRENCY_CHOICES
from .models import (Category, Product, Review, Order)
from .utils import (user_in_group, get_orders_by_user, get_products_by_supplier, paginator_helper,
                    create_product_from_http_request, get_choices, add_product_to_cart, close_order,
                    get_average_score_by_supplier, get_number_of_orders_on_product, update_product_from_http_request,
                    get_products_by_supplier_username)


class IndexView(generic.ListView):
    template_name = 'ecommerce/index.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.get_hot_category(10)


def orders_view(request):
    orders = []
    if request.user.is_authenticated:
        orders = paginator_helper(request, get_orders_by_user(request.user))
        context = {'orders': orders}
        return render(request, 'ecommerce/order_list.html', context)
    return redirect('ecommerce:login')


def order_detail(request, order_id: int):
    products = []
    context = {}
    if request.user.is_authenticated:
        order: Order = Order()
        try:
            order = Order.objects.get(id=order_id)
        except Order.DoesNotExist:
            redirect('ecommerce:index')

        if order.buyer_id != request.user.id:
            return redirect('ecommerce:index')

        if order:
            products = paginator_helper(request, order.products.all())
            context = {
                'products': products,
                'order': order
            }
            if request.method == 'POST':
                close_order(order_id)
                return redirect('ecommerce:index')

    return render(request, 'ecommerce/order_detail.html', context)


def cancel_order(request, order_id: int):
    if request.user.is_authenticated:

        order: Order = Order.objects.get(id=order_id)
        if order.buyer_id != request.user.id:
            return redirect('ecommerce:index')

        order.delete()

    return redirect('ecommerce:index')


def supplier_overview(request, username: str):
    context = {}
    if request.user.is_authenticated:
        context['supplier_username'] = username
        context['average_score'] = range(0, int(get_average_score_by_supplier(username)['score__avg']))
        context['products'] = paginator_helper(request, get_products_by_supplier_username(username))

        return render(request, 'ecommerce/supplier_overview.html', context)
    return redirect('ecommerce:index')


@transaction.atomic
def add_product_to_cart_request(request, product_id):
    if request.user.is_authenticated and request.method == 'POST':
        user = request.user
        if user_in_group(user, 'Customer'):
            add_product_to_cart(user, product_id)

    return redirect('ecommerce:product', product_id=product_id)


@transaction.atomic
def signup_view(request):
    if request.user.is_authenticated:
        redirect('ecommerce:index')

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('ecommerce:index')

    else:
        form = MyUserCreationForm()

    context = {'form': form}
    return render(request, 'ecommerce/registration/sign_up.html', context)


def category(request, category_id):
    products = paginator_helper(request,
                                Product.objects.filter(category__name=category_id).order_by('-score').all(), 10)
    context = {'products': products,
               'category_id': category_id}
    return render(request, 'ecommerce/category_products.html', context)


def edit_product_view(request, product_id):
    if request.user.is_authenticated:
        user = request.user

        if user_in_group(user, 'Supplier'):
            product = get_object_or_404(Product, pk=product_id)
            if product.supplier_id == request.user.id:
                context = {}
                if request.method == 'GET':
                    form = ProductForm()

                    context = {'name': product.name,
                               'manufacturer': product.manufacturer.name,
                               'model': product.model.name,
                               'category': product.category.name,
                               'price': product.price,
                               'description': product.description}

                    return render(request, 'ecommerce/form_edit_product.html', context)
                if request.method == 'POST':
                    update_product_from_http_request(request, product_id)
                    return redirect('ecommerce:index')

    return redirect('ecommerce:index')


def product_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    try:
        reviews = get_list_or_404(Review, product=product_id)
    except Http404:
        reviews = []

    reviews = paginator_helper(request, reviews, 10)
    form = ReviewForm()
    gallery_images = product.gallery
    context = {'product': product,
               'recommendations': product.get_recommendation(3),
               'reviews': reviews,
               'gallery_images': gallery_images,
               'sell_number': get_number_of_orders_on_product(product_id),
               'form': form}

    return render(request, 'ecommerce/product.html', context)


@transaction.atomic
def submit_review(request, product_id):
    if request.method == 'POST':
        product = Product.objects.get(id=str(product_id))
        if request.user.username != product.supplier.username:
            form = ReviewForm(request.POST, request.FILES)

            if form.is_valid():
                author = request.user.username
                form.cleaned_data['author'] = author
                form.cleaned_data['supplier'] = product.supplier.username
                form.cleaned_data['author'] = author
                form.cleaned_data['product'] = product.id

                form.save()

    return redirect('ecommerce:product', product_id=product_id)


def search_view(request):
    products = []
    context = {}
    if request.method == 'GET':
        search_query = request.GET.get('searchbox', '')
        context['search_query'] = search_query
        products = paginator_helper(request, Product.objects.filter(
            Q(name__contains=search_query) |
            Q(model__manufacturer__name__contains=search_query) |
            Q(model__name__contains=search_query) |
            Q(supplier__username__contains=search_query)).order_by('score'))
    context['products'] = products
    return render(request, 'ecommerce/products.html', context)


def profile_view(request):
    user = request.user
    if user.is_authenticated:
        customer = "Customer"
        if user_in_group(user, customer):
            orders = paginator_helper(request, get_orders_by_user(user), 5)
            context = {'orders': orders}
            return render(request, 'ecommerce/customer_profile.html', context)
        else:
            message = ""
            context = {}
            try:
                handle_product_form(request, context)
            except IntegrityError:
                message = 'You are already selling this product.'

            products = paginator_helper(request, get_products_by_supplier(user), 5)
            average_score = get_average_score_by_supplier(user.username)['score__avg']

            if average_score is None:
                average_score = 0

            context['products'] = products
            context['currency_choices'] = get_choices(CURRENCY_CHOICES)
            context['average_score'] = range(0, int(average_score))

            return render(request, 'ecommerce/supplier_profile.html', context)

    return redirect('ecommerce:index')


def handle_product_form(request, context):
    if request.method == 'GET':
        context['form'] = ProductForm()
    elif request.method == 'POST':
        create_product_from_http_request(request)

ecommerce/templates/ecommerce/add_to_cart_button.html
<span>
    <form method="post" action="{% url 'ecommerce:add_to_cart' product_id=product_id %}">
        {% csrf_token %}
        {% include 'ecommerce/form_submit_button.html' with label='Buy' %}
    </form>
</span>

ecommerce/templates/ecommerce/category_products.html
{% extends 'base.html' %}
{% block head %}
<title>ecommerce | {{ category_id }}</title>
{% endblock %}

{% block body %}
    <div class="mdl-card mdl-shadow--8dp center" style="min-height: 1em;">
        <div class="mdl-card__title">
            <h1 class="mdl-card__title-text">
                Products in category: '{{ category_id }}'
            </h1>
        </div>
    {% include 'ecommerce/product_list.html' with products=products %}
    </div>
{% endblock %}

ecommerce/templates/ecommerce/customer_profile.html
{% extends "base.html" %}
{% block body %}
    <div class="mdl-card-wide-detail mdl-shadow--8dp center">
        <div class="mdl-card__title">
            <div class="mdl-card__title-text">
                <h1 class="mdl-card__title-text">My Orders</h1>
            </div>
        </div>
    </div>

    {% include 'ecommerce/order_list.html' with orders=orders %}
{% endblock %}

ecommerce/templates/ecommerce/form_attach_file_element.html
<div class="mdl-textfield mdl-js-textfield">
    <input class="mdl-textfield__input" placeholder="{{ placeholder }}" readonly style="box-sizing: border-box;">
    <div class="mdl-button mdl-button--icon mdl-button-primary" style="right: 0">
        <i class="material-icons">attach_file</i>
        <input class="mdl-input--file" {{ required|yesno:"required," }} {{ multiple|yesno:"multiple," }} type="file"
               name="{{ name }}" id="id_{{ name }}">
    </div>
</div>

ecommerce/templates/ecommerce/form_edit_product.html
{% extends 'base.html' %}

{% block body %}
    <div class="mdl-card mdl-shadow--8dp center">
        <div class="mdl-card__title">
            <h1 class="mdl-card__title-text">Edit Product: {{ product.name }}</h1>
        </div>
        <div style="margin:1em">
            <form action="." method="POST">
                {% csrf_token %}

                {% include 'ecommerce/form_text_element.html' with label='Name' name='name' readonly=True value=name %}

                {% include 'ecommerce/form_text_element.html' with label='Manufacturer' name='manufacturer' value=manufacturer readonly=True %}

                {% include 'ecommerce/form_text_element.html' with label='Model' name='model' readonly=True value=model %}

                {% include 'ecommerce/form_text_element.html' with label='Category' name='category' value=category %}

                {% include 'ecommerce/form_number_element.html' with label='Price' name='price' value=price %}

                {% include 'ecommerce/form_textarea_element.html' with label='Description' name='description' value=description %}

                {% include 'ecommerce/form_submit_button.html' with label='Confirm' %}
            </form>
        </div>
    </div>
{% endblock %}

ecommerce/templates/ecommerce/form_number_element.html
<div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <span>
            <input type="number" min="{{ min }}" max="{{ max }}" required
                   name="{{ name }}" id="id_{{ name }}" class="mdl-textfield__input"
                   {% if value %}value="{{ value }}"{% endif %}>
            <label class="mdl-textfield__label" for="id_{{ name }}">{{ label }}</label>
        </span>
    </div>
</div>

ecommerce/templates/ecommerce/form_radio_select.html
<div>
    {% for item in radiobox %}
        <div style="margin: 0.5em;" onclick="changeState('id_{{ name }}_{{ forloop.counter0 }}')">
            <label class="mdl-radio mdl-js-radio">
                <input id="id_{{ name }}_{{ forloop.counter0 }}" name="{{ name }}" type="radio" value="{{ forloop.counter }}" required class="mdl-radio__button">
                <span class="mdl-radio__label">{{ item.choice_label }}</span>
            </label>
        </div>
    {% endfor %}
<script>
function changeState(elementId) {
    for (var element in document.getElementsByClassName('radio')) {
        element.setAttribute('checked', false);
    }

    element = document.getElementById(elementId);
    if (!element.getAttribute('checked')) {
        element.setAttribute('checked', true);
    }
}
</script>
</div>

ecommerce/templates/ecommerce/form_text_element.html
<div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <input {% if type %} type="{{ type }}" {% else %} type="text" {% endif %}
               {% if pattern %} pattern="{{ pattern }}" {% endif %}
                  required class="mdl-textfield__input" name="{{ name }}" id="id_{{ name }}" {{ readonly|yesno:"readonly,"}}
                {% if value %}value="{{ value }}"{% endif %}>
        <label class="mdl-textfield__label" for="id_{{ name }}">{{ label }}</label>
    </div>
</div>

ecommerce/templates/ecommerce/order_detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="mdl-card-wide-detail mdl-shadow--8dp">
        <div class="mdl-card__title">
            <h1 class="mdl-card__title-text">Order: {{ order.id }}</h1>
        </div>
        <div class="mdl-card__subtitle-text" style="margin: 1em">
            <h1 class="mdl-card__subtitle-text">{{ order.date }}</h1>
        </div>
        {% if order.open %}
            <div style="margin: 1em;">
                <span style="margin:1em;">
                    <form action="{% url 'ecommerce:close_order' order.id %}" method="POST">
                        {% csrf_token %}
                        {% include 'ecommerce/form_submit_button.html' with label='Confirm Order' %}
                    </form>
                </span>
                <span style="margin:1em;">
                    <form action="{% url 'ecommerce:cancel_order' order.id %}" method="POST">
                        {% csrf_token %}
                        {% include 'ecommerce/form_submit_button.html' with label='Cancel Order' %}
                    </form>
                </span>
            </div>
        {% endif %}

        {% include 'ecommerce/product_list.html' %}
    </div>
{% endblock %}

ecommerce/templates/ecommerce/order_list.html
<ul class="mdl-list">
    {% for order in orders %}
        <li class="mdl-list__item mdl-shadow--2dp" style="margin: 1em">
            <div>
                <div class="mdl-card__title">
                    <h1 class="mdl-card__title-text">
                        <a href="{% url 'ecommerce:order' order.id %}">
                        Order: {{ order.id }}
                        </a>
                    </h1>
                </div>
            </div>
        </li>
    {% endfor %}
</ul>
{% if not orders %}
    <div class="mdl-card-wide-detail mdl-shadow--8dp center">
        <div class="mdl-card__title">
            <h1 class="mdl-card__title-text">
                No orders done, yet.
            </h1>
        </div>
    </div>
{% endif %}

ecommerce/templates/ecommerce/product.html
{% extends "base.html" %}
{% block head %}
<title>ecommerce | {{ product.name }}</title>
{% endblock %}

{% block body %}
    <div id="content-product" class="mdl-card mdl-card-wide-detail mdl-shadow--8dp center">
        <div id="content-product-header" class="mdl-card__title" align="center">
            <h1 class="mdl-card__title-text"> {{ product.name }} </h1>
            <span class="mdl-card__subtitle-text" style="margin-left: 1em;">({{ sell_number }})</span>
            <div class="mdl-layout-spacer"></div>
            <a href="{% url 'ecommerce:supplier_overview' product.supplier.username %}">{{ product.supplier.username }}</a>
        </div>
        <div id="content-product-info" class="mdl-card__subtitle-text" style="margin-left: 1em;">
            <h8>{{ product.manufacturer.name }}</h8>
            <h8>{{ product.model.name }}</h8>
        </div>
        <div id="content-product-score" class="mdl-card__subtitle-text" style="margin-left: 1em;">
            <i class="material-icons">
                {% for i in  product.get_score %}
                    star
                {% endfor %}
            </i>
        </div>
        {% if not product.sale > 0 %}
            <div style="margin-left: 1em">
                <span>{{ product.price }} {{ product.currency }}</span>
                {% include 'ecommerce/add_to_cart_button.html' with product_id=product.id %}
            </div>
        {% else %}
            <div style="margin-left: 1em">
                <span>{{ product.sale }} {{ product.currency }}</span>
                {% include 'ecommerce/add_to_cart_button.html' with product_id=product.id %}
            </div>
        {% endif %}
        {% if product.cover %}
        <div id="content-product-cover" class="mdl-card__media center" style="background:white;">
            <img src="{{ product.cover.url }}" style="max-width: 50%; max-height: 40em;"/>
        </div>
        {% endif %}
        {% if not gallery_images %}
        <div id="content-product-galley" class="mdl-card__media">
            {% for image in gallery_images %}
            <div id="content-product-gallery-picture-{{ image.id }}">
                <img src="{{ image.image.url }}" class="thumbnail"/>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        {% if product.description %}
            <div id="content-product-description" class="mdl-card__supporting-text center">
                <p class="mdl-typography--text-justify">{{ product.description }}</p>
            </div>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <div class="mdl-card mdl-shadow--8dp center">
            <div class="mdl-card__title">
                <h1 class="mdl-card__title-text">Products other users has bought this with</h1>
            </div>

            {% include 'ecommerce/product_list.html' with products=recommendations skip_footer=True %}
        </div>
        {% if product.supplier.username != request.user.username %}
            {% include 'ecommerce/review_form.html' with form=form product=product %}
        {% endif %}
        {% include 'ecommerce/review_list.html' with reviews=reviews %}
    {% endif %}
{% endblock %}

ecommerce/templates/ecommerce/product_list.html
<ul class="mdl-list">
    {% for product in products %}
        <li class="mdl-list__item mdl-shadow--2dp" style="margin: 1em">
            <div style="margin: 1em">
                <span class="mdl-list__item-primary-content">
                    <a href="{% url 'ecommerce:product' product.id %}">
                        {{ product.name }}
                    </a>
                    {% if user.is_authenticated %}
                        {% if product.supplier.username ==  user.username %}
                            <a href="{% url 'ecommerce:edit_product' product.id %}"><i class="material-icons" >mode_edit</i></a>
                        {% endif %}
                    {% endif %}
                </span>
                {% if not product.sale > 0 %}
                    <div>
                        <p>{{ product.price }} {{ product.currency }}</p>
                    </div>
                {% else %}
                    <div>
                        <p>{{ product.sale }} {{ product.currency }}</p>
                    </div>
                {% endif %}
                <div>
                    <a class="mdl-list__item-secondary-content" href="#">
                        <i class="material-icons">
                            {% for i in product.get_score %}
                                star
                            {% endfor %}
                        </i>
                    </a>
                </div>
            </div>
            <div>
                <img class="thumbnail" src="{{ product.cover.url }}" />
            </div>
        </li>
    {% endfor %}
</ul>

{% if not skip_footer %}
    {% include "ecommerce/paginator_footer.html" with item=products %}
{% endif %}

ecommerce/templates/ecommerce/review_form.html
<div id="content-form-review" class="mdl-card mdl-shadow--8dp center" style="min-height: 0">
    <script type="text/javascript">
        function showReviewForm() {
            var reviewFormId = document.getElementById("contentPanelReviewForm");
            inlineStyle = "block";
            if(reviewFormId.style.display === inlineStyle) {
                var inlineStyle = "none";
            }
            reviewFormId.style.display = inlineStyle;

            if (inlineStyle === "block") {
                document.getElementById("id_text").focus();
            }
        }
    </script>
    <div id="content-review-header" class="mdl-card__title" align="center">
        <h1 class="mdl-card__title-text" onclick="showReviewForm()"> Insert new review </h1>
    </div>

    <div id="contentPanelReviewForm" class="mdl-card__supporting-text" style="display: none" enctype="multipart/form-data">
        <form id="reviewFormId" method="post" action="{% url 'ecommerce:submit_review' product_id=product.id %}">
            {% csrf_token %}

            {% include 'ecommerce/form_textarea_element.html' with name='text' label='Review' rows='3' cols='80' %}

            {% include 'ecommerce/form_number_element.html' with name='score' label='Score' min='1' max='5' %}

            {% include 'ecommerce/form_attach_file_element.html' with placeholder='Choose File' %}

            {% include 'ecommerce/form_submit_button.html' with label='Submit' %}
        </form>
    </div>
</div>

ecommerce/templates/ecommerce/supplier_overview.html
{% extends "base.html" %}

{% block body %}
    <div class="mdl-card mdl-shadow--8dp center">
        <div class="mdl-card__title">
            <div class="mdl-card__title-text">Overview of supplier: {{ supplier_username }}</div>
        </div>
        <div class="mdl-card__subtitle-text" style="margin-left: 1em;">
            Average score review:
            <i class="material-icons">
                {% for i in average_score %}
                    star
                {% endfor %}
            </i>
        </div>

    {% include 'ecommerce/product_list.html' with products=products %}
    </div>
{% endblock %}